openapi: 3.0.3
info:
  title: Cloud Guard API
  version: 1.0.0
  description: >-
    The Cloud Guard server that provide API for the client. Made with NodeJS,
    Express and Swagger.
servers:
  - url: http://localhost:3001/api
security:
  - bearerAuth: []
tags:
  - name: S3
    description: Operations related to S3 service
  - name: Cognito
    description: Operations related to Cognito service
paths:
  /s3/bucket/{bucketType}/objects:
    get:
      tags:
        - S3
      summary: Get list of objects for S3 bucket
      description: Retrieves a list of objects for the specified S3 bucket.
      produces:
        - application/json
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket (storage or personal vault)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /s3/bucket/{bucketType}/objects/{objectKey}:
    get:
      tags:
        - S3
      summary: Download S3 Object
      description: Downloads an object from the specified S3 bucket.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket. (storage or personal vault)
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: The key/name of the object in the S3 bucket.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - S3
      summary: Create a multipart uploading.
      description: Create a multipart uploading to S3.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket. (storage or personal vault)
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: The key/name of the object in the S3 bucket.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      tags:
        - S3
      summary: Upload part of a multipart object
      description: Uploads a part of a multipart object to the specified S3 bucket.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket. (storage or personal vault)
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: The key/name of the object in the S3 bucket.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - S3
      summary: Complete Multipart Upload
      description: Completes a multipart upload for an object in the specified S3 bucket.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket. (storage or personal vault)
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: The key/name of the object in the S3 bucket.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - S3
      summary: Delete S3 Object
      description: Deletes an object from the specified S3 bucket.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket. (storage or personal vault)
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: The key/name of the object in the S3 bucket.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
                description: Indicates if the object was successfully deleted (true).
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /s3/bucket/{bucketType}/objectService/{objectKey}/func/image:
    get:
      tags:
          - S3
      summary: Get image preview from S3 bucket.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: Type of the bucket.
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: Key of the object in the bucket.
      responses:
        '200':
          description: Image base64 preview.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /s3/bucket/{bucketType}/objectService/{objectKey}/func/createFolder:
    put:
      tags:
        - S3
      summary: Create Folder in S3 Bucket
      description: Creates a folder in the specified S3 bucket.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket. (storage or personal vault)
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: The key/name of the parent folder in the S3 bucket where the new folder will be created.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /s3/bucket/{bucketType}/objectService/{objectKey*}/func/shareFolder:
    post:
      tags:
        - S3
      summary: Share Folder in S3 Bucket
      description: Shares a folder in the specified S3 bucket with other users.
      parameters:
        - in: path
          name: bucketType
          required: true
          schema:
            type: string
          description: The type of the S3 bucket. (storage or personal vault)
        - in: path
          name: objectKey
          required: true
          schema:
            type: string
          description: The key/name of the folder in the S3 bucket to be shared.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /cognito/user:
    get:
      tags:
        - Cognito
      summary: Get user information from Cognito
      description: Retrieves information about the current authenticated user from Cognito.
      produces:
        - application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CognitoUserDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: The error message
        stack:
          type: string
          description: The error stack
    CognitoUserDetails:
      type: object
      properties:
        UserAttributes:
          type: array
          items:
            type: object
            properties:
              Name:
                type: string
                description: The name of the attribute
              Value:
                type: string
                description: The value of the attribute
        Username:
          type: string
          description: The username