openapi: 3.0.3
info:
  title: Cloud Guard API
  version: 1.0.0
  description: >-
    The Cloud Guard server that provide API for the client. Made with NodeJS,
    Express and Swagger.
servers:
  - url: http://localhost:3001/api
security:
  - bearerAuth: []
tags:
  - name: S3
    description: Operations related to S3 service
  - name: Cognito
    description: Operations related to Cognito service
paths:
  /s3/bucket:
    post:
      tags:
        - S3
      summary: Create S3 bucket for the specific user
      description: Creates an S3 bucket for the specific user.
      produces:
        - application/json
      requestBody:
        description: Create a new S3 bucket
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/S3BucketCreation'
      responses:
        '201':
          description: Bucket created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/S3BucketCreationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /s3/bucket/{name}/objects:
    get:
      tags:
        - S3
      summary: Get list of objects for S3 bucket
      description: Retrieves a list of objects for the specified S3 bucket.
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: The name of the S3 bucket
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/S3Object'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /cognito/user:
    get:
      tags:
        - Cognito
      summary: Get user information from Cognito
      description: Retrieves information about the current authenticated user from Cognito.
      produces:
        - application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CognitoUserDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    S3BucketCreation:
      type: object
      properties:
        name:
          type: string
          description: The name of the S3 bucket
    S3BucketCreationResponse:
      type: object
      properties:
        Location:
          type: string
          description: The URL/location of the created bucket
    S3Object:
      type: object
      properties:
        Key:
          type: string
          description: The key/name of the object
        Size:
          type: integer
          description: The size of the object in bytes
        LastModified:
          type: string
          description: The object last modified date
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: The error message
        stack:
          type: string
          description: The error stack
    CognitoUserDetails:
      type: object
      properties:
        UserAttributes:
          type: array
          items:
            type: object
            properties:
              Name:
                type: string
                description: The name of the attribute
              Value:
                type: string
                description: The value of the attribute
        Username:
          type: string
          description: The username